allow cli options for filtering and numbering. add a nicer header

diff --git a/.bin/tprint b/.bin/tprint
--- a/.bin/tprint
+++ b/.bin/tprint
@@ -2,7 +2,62 @@
 #
 # simple script to print text files
 #
-header="$1 : `date | cut --fields=2,3,4,5,6 -d ' '` "
-fname="/tmp/${UID}-enscript-tmp.ps"
-enscript -b "${header}" -Ec -C --word-wrap -f Courier7 -p ${fname} "$1" 
-lpr -r $fname 
+MINARG="1"
+USAGE="-e \ntprint [-C] <filename>\n"
+INFILE=""
+
+# base enscript and lpr options
+# -Ec filters for c files
+OPTS_ENSCRIPT="-T 2 -f Courier8 --word-wrap"
+OPTS_LPR="-r"
+
+printer() {
+
+# FIXME: can't get a footer to work here.
+HEADER="$(basename "$1"):||   `date +%H%M\ %B,\ %d\ %Y`  Page $% of $="
+FNAME="/tmp/${UID}-enscript-tmp.ps"
+
+# enscript -b "${HEADER}" -Ec -C --word-wrap -f Courier7 -p ${FNAME} "$1" 
+enscript -b "${HEADER}" ${OPTS_ENSCRIPT}  -p ${FNAME} "$1" 
+exit 0
+lpr ${OPTS_LPR} ${FNAME}
+exit 0
+
+}
+
+if [ "$#" -ge "$MINARG" ] ; then
+
+  while [ "$#"  -gt "0" ] ; do
+
+		case $1 in
+
+      -E* )
+				OPTS_ENSCRIPT="${OPTS_ENSCRIPT} $1"
+        ;;
+			-C  )
+				OPTS_ENSCRIPT="${OPTS_ENSCRIPT} -C"
+        ;;
+
+			--help | '-h' )
+				echo $USAGE
+        exit 1
+			;;
+
+      # filename given
+			* )
+        if [ -e "$1" ] ; then 
+          printer $1
+        else
+          echo "TPRINT ERROR: File $1 does not exist!"
+          exit 1
+        fi
+			;;
+
+		esac
+    shift
+	done
+
+else
+	echo $USAGE
+	exit 1
+fi
