better option parsing, add pdf mode

diff --git a/.bin/tprint b/.bin/tprint
--- a/.bin/tprint
+++ b/.bin/tprint
@@ -3,7 +3,7 @@
 # simple script to print text files
 #
 MINARG="1"
-USAGE="-e \n\ttprint [-C][-E<filter>] <filename>\n"
+USAGE="-e \n\ttprint [-C][-E<filter>[-F<fontsize>][-pdf] <filename>\n"
 INFILE=""
 
 # base enscript and lpr options
@@ -11,53 +11,75 @@ INFILE=""
 OPTS_ENSCRIPT="-T 2 -f Courier8 --word-wrap"
 OPTS_LPR="-r"
 
+PDF=""
+
 printer() {
 
-# FIXME: can't get a footer to work here.
-HEADER="$(basename "$1"):||   `date +%H%M\ %B,\ %d\ %Y`  Page $% of $="
-FNAME="/tmp/${UID}-enscript-tmp.ps"
+    # FIXME: can't get a footer to work here.
+    HEADER="$(basename "$1"):||   `date +%H%M\ %B,\ %d\ %Y`  Page $% of $="
+    FNAME="/tmp/${UID}-enscript-tmp.ps"
 
-# enscript -b "${HEADER}" -Ec -C --word-wrap -f Courier7 -p ${FNAME} "$1" 
-enscript -b "${HEADER}" ${OPTS_ENSCRIPT}  -p ${FNAME} "$1" 
-exit 0
-lpr ${OPTS_LPR} ${FNAME}
-exit 0
+    # enscript -b "${HEADER}" -Ec -C --word-wrap -f Courier7 -p ${FNAME} "$1" 
+    enscript -b "${HEADER}" ${OPTS_ENSCRIPT}  -p ${FNAME} "$1" 
+    lpr -o PageSize=Letter ${OPTS_LPR} ${FNAME}
+    exit 0
 
 }
 
 if [ "$#" -ge "$MINARG" ] ; then
 
-  while [ "$#"  -gt "0" ] ; do
+    while [ "$#"  -gt "0" ] ; do
 
-		case $1 in
+        case $1 in
 
-      -E* )
-				OPTS_ENSCRIPT="${OPTS_ENSCRIPT} $1"
-        ;;
-			-C  )
-				OPTS_ENSCRIPT="${OPTS_ENSCRIPT} -C"
-        ;;
+            -E* )
+            # set the filter
+            OPTS_ENSCRIPT="${OPTS_ENSCRIPT} $1"
+            ;;
 
-			--help | '-h' )
-				echo $USAGE
-        exit 1
-			;;
+            -C  )
+            # number the lines
+            OPTS_ENSCRIPT="${OPTS_ENSCRIPT} -C"
+            ;;
 
-      # filename given
-			* )
-        if [ -e "$1" ] ; then 
-          printer $1
-        else
-          echo "TPRINT ERROR: File $1 does not exist!"
-          exit 1
-        fi
-			;;
+            -F* )
+            # adjust the font size
+            fontsize="$(echo $1 | cut -f 2 -d 'F')"
+            OPTS_ENSCRIPT="$(echo $OPTS_ENSCRIPT | sed s/Courier./Courier${fontsize}/)"
+            ;;
 
-		esac
-    shift
-	done
+            -pdf )
+            # create a pdf instead of printing to lpr
+            PDF="1"
+            ;;
+
+            -* | --help | '-h' )
+            echo $USAGE
+            exit 1
+            ;;
+
+            # filename given
+            * )
+            if [ -e "$1" ] ; then 
+                printer $1
+            else
+                echo "TPRINT ERROR: File $1 does not exist!"
+                exit 1
+            fi
+            ;;
+
+        esac
+        shift
+    done
 
 else
-	echo $USAGE
-	exit 1
+    echo $USAGE
+    exit 1
 fi
+
+
+
+
+
+
+# vim:set filetype=sh textwidth=80 fdm=syntax tabstop=4 shiftwidth=4 expandtab smarttab autoindent smartindent:
